version: '3.8'

services:
  pda-partner:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: pda-partner
    environment:
      # 환경변수는 .env 파일에서 로드
      - SHEETS_KEY_PATH=${SHEETS_KEY_PATH}
      - DRIVE_KEY_PATH=${DRIVE_KEY_PATH}
      - SPREADSHEET_ID=${SPREADSHEET_ID}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASS=${EMAIL_PASS}
      - RECEIVER_EMAIL=${RECEIVER_EMAIL}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
      - KAKAO_ACCESS_TOKEN=${KAKAO_ACCESS_TOKEN}
      - KAKAO_REFRESH_TOKEN=${KAKAO_REFRESH_TOKEN}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_REPO=${GITHUB_REPO}
      - TEST_MODE=${TEST_MODE:-false}
      - LIMIT=${LIMIT:-1}
      - GENERATE_GRAPHS=${GENERATE_GRAPHS:-auto}
      - GITHUB_UPLOAD=${GITHUB_UPLOAD:-auto}
    volumes:
      - ../config:/app/config:ro  # 서비스 계정 키 파일 마운트
      - ../output:/app/output     # 출력 파일 저장
      - ../logs:/app/logs         # 로그 파일 저장
    restart: unless-stopped
    
  # 크론잡 스케줄러 (선택사항)
  pda-partner-scheduler:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: pda-partner-scheduler
    environment:
      - SHEETS_KEY_PATH=${SHEETS_KEY_PATH}
      - DRIVE_KEY_PATH=${DRIVE_KEY_PATH}
      - SPREADSHEET_ID=${SPREADSHEET_ID}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASS=${EMAIL_PASS}
      - RECEIVER_EMAIL=${RECEIVER_EMAIL}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
      - KAKAO_ACCESS_TOKEN=${KAKAO_ACCESS_TOKEN}
      - KAKAO_REFRESH_TOKEN=${KAKAO_REFRESH_TOKEN}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_REPO=${GITHUB_REPO}
      - TEST_MODE=false
      - LIMIT=1
      - GENERATE_GRAPHS=auto
      - GITHUB_UPLOAD=auto
    volumes:
      - ../config:/app/config:ro
      - ../output:/app/output
      - ../logs:/app/logs
    command: >
      sh -c "
      echo '0 5 * * * cd /app && python PDA_partner.py' > /etc/crontabs/root &&
      crond -f
      "
    restart: unless-stopped 